Add missing files and fix typos
Remove circleci configuration. Add missing precommit file. And fix the
test GitHub Action file

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -2,6 +2,7 @@ name: Test
 on: [push, pull_request]
 permissions:
   contents: read
+  pull-requests: write
 
 jobs:
   test:
@@ -10,11 +11,14 @@ jobs:
         go-version: [ "1.25.x", "1.26.x" ]
     runs-on: "ubuntu-latest"
     steps:
+      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v4
+        with:
+          persist-credentials: false
       - name: Install Go
         uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v5
         with:
           go-version: ${{ matrix.go-version }}
-      - name: Test
+      - name: Run tests with coverage
         run: make coverage
       - name: Upload coverage reports to Codecov
         uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7 # v5
@@ -22,19 +26,21 @@ jobs:
           token: ${{ secrets.CODECOV_TOKEN }}
           files: "./coverage.out"
       - name: Post coverage to GitHub comment
-        if: github.event_name == "pull_request"
+        if: github.event_name == 'pull_request'
         env:
           URL: ${{ github.event.pull_request.html_url }}
-          GH_TOKEN: %{{ github.token }}
+          GH_TOKEN: ${{ github.token }}
         run: |
-          echo "\`\`\`\n$(go tool cover --func=coverage.out)\n\`\`\`" | gh pr comment "$URL" --body-file=- --delete-last --yes
+          actual_pct="$(go tool cover --func=coverage.out | awk '/^total:.*%$/ { print substr($3, 1, length($3)-1) }')"
+          gh pr comment "$URL" --delete-last --yes || true
+          echo -e "Total Coverage: $actual_pct\n<details><summary>Function Coverage Breakdown</summary>\n\n\`\`\`\n$(go tool cover --func=coverage.out)\n\`\`\`\n\n</details>" | gh pr comment "$URL" --body-file=-
       - name: Require minimum test coverage percentage
         env:
           TESTCOVERAGE_PCT: 94
         run: |
           actual_pct="$(go tool cover --func=coverage.out | awk '/^total:.*%$/ { print substr($3, 1, length($3)-1) }')"
           echo "Verifying test coverage percentage (minimum allowed: ${TESTCOVERAGE_PCT} ; parsed: ${actual_pct})"
-          # NOTE: sys.exit(True) will be a non-zero exit code, so we only want
-          # that when the actual percentage is lower than our configured
-          # threshold
           python -c "import sys; sys.exit($actual_pct < $TESTCOVERAGE_PCT)"
+        # NOTE: sys.exit(True) will be a non-zero exit code, so we only want
+        # that when the actual percentage is lower than our configured
+        # threshold
